title: VisHub Lab Edinburgh
description: >-
  Interdisciplinary research lab in data visualization and HCI at the University of Edinburgh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vishub.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vishublab
github_username: visualinteractivedata
theme: jekyll-theme-minimal
logo: "assets/logos/vishub-logo.svg"
repository: visualinteractivedata/visualinteractivedata.github.io
github: [metadata]
relative_links:
  enabled: true
  collections: true
plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
collections:
  projects:
    output: true
    order:
      - dashboards.md
      - tools.md
      - education.md
      - networks.md
      - covid19_vis.md
      - data_comics.md
      - geographic.md
      - immersive_analytics.md
      - peace_analytics.md
      - clinical_guidelines.md
  vishubprojects:
    output: true
    order:
      - mailinglist.md
      - professionals_course.md
      - datafairs.md
      - datavismeetup.md
      - chartclinic.md
