theme: jekyll-theme-minimal
logo: "figures/logo-feb2022.png"
repository: visualinteractivedata/visualinteractivedata.github.io
github: [metadata]
gems: ["jemoji"]
relative_links:
  enabled: true
  collections: true
plugins: [jekyll-seo-tag]
collections:
  projects:
    output: true
    order:
      - dashboards.md
      - tools.md
      - education.md
      - networks.md
      - covid19_vis.md
      - data_comics.md
      - geographic.md
      - immmersive_analytics.md
      - peace_analytics.md
      - clinical_guidelines.md
  vishubprojects:
    output: true
    order:
      - professionals_course.md
      - datafairs.md
      - datavismeetup.md
      - chartclinic.md
